name: Pousse la version web vers GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install love.js
        run: npm install -g love.js
      - name: Build js
        run: make js
      - name: Upload GitHub Pages artifact
        # https://github.com/marketplace/actions/upload-github-pages-artifact
        # https://github.com/actions/upload-pages-artifact/blob/main/action.yml
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: dist/js


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        # https://github.com/marketplace/actions/deploy-github-pages-site
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
